# .github/workflows/build.yml
name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: [ self-hosted, Windows, X64 ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run build script
        run: node scripts/build.mjs --ci

      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: |
            packages/*/dist
            packages/*/*/dist
            packages/*/*/*/dist