# .github/workflows/lint.yml
name: Lint code

on:
  push:

jobs:
  lint:
    runs-on: [ self-hosted, Windows, X64 ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          set-safe-directory: false

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: TypeScript type check
        run: npx tsc --noEmit

      - name: Run ESLint
        run: npx eslint . --ext .ts,.tsx